[package]
name = "pwt-macros"
version = "0.3.0"
edition = "2021"
license = "MIT OR Apache-2.0"
exclude = [ "debian" ]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
syn = { version = "2" , features = [ "extra-traits" ] }
quote = "1"

[dev-dependencies]
trybuild = "1"
yew = "0.21"
